### ISSUE TITLE
API4 Plugin wont show kagerou

### ISSUE THREAD

**Issue by seathasky** [ackwell/BrowserHost#23]
**Updated:** Finally was able to get it installed and now it just doesnt show kagerou. I have the correct WS url, i tested in a web browser and it shows fine. Tested in Linux (FF14 Wine 6 Lutris install) and on Mac Crossover as well!

![Screen Shot 2021-10-03 at 1 23 26 AM](https://user-images.githubusercontent.com/17598024/135741138-aa45d8ba-3ef5-445c-bf15-c5ac133d0897.png)

![Screen Shot 2021-10-03 at 1 27 04 AM](https://user-images.githubusercontent.com/17598024/135741222-6dff2ef6-68f4-49ca-b39e-e8ec53486f22.png)
Frame transport stuck on initialising

**Comment by seathasky** [comment]
Any word on this?

**Comment by seathasky** [comment]
GOOD TALK!

**Comment by seathasky** [comment]
![Screen_Shot_2021-10-11_at_1 06 18_PM](https://user-images.githubusercontent.com/17598024/136882786-fda8a8fa-526e-4c36-b42f-30e7edb9fd31.png)

**Dalamund log:**
as for dalmund log, 2021-10-11 22:29:00.672 -04:00 [INF] [TriadBuddy] Loaded game data for cards:327, npcs:102
2021-10-11 22:29:01.800 -04:00 [INF] [BrowserHost.Plugin] Installing dependencies...
2021-10-11 22:29:01.803 -04:00 [INF] [BrowserHost.Plugin] Downloading cef 89.0.17+ge7bbb1d+chromium-89.0.4389.114
2021-10-11 22:29:04.818 -04:00 [INF] [BrowserHost.Plugin] Dependency install Complete.
2021-10-11 22:29:06.160 -04:00 [INF] [System.Diagnostics.Process] [Render]: Render process running.
2021-10-11 22:29:06.510 -04:00 [INF] [System.Diagnostics.Process] [Render]: Watching parent PID 1120
2021-10-11 22:29:06.551 -04:00 [ERR] [System.Diagnostics.Process] [Render]: 
2021-10-11 22:29:06.560 -04:00 [ERR] [System.Diagnostics.Process] [Render]: Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
2021-10-11 22:29:06.560 -04:00 [ERR] [System.Diagnostics.Process] [Render]:    at SharpDX.Direct3D11.D3D11.D3D11CreateDevice_(Void* param0, Int32 param1, Void* param2, Int32 param3, Void* param4, Int32 param5, Int32 param6, Void* param7, Void* param8, Void* param9)
2021-10-11 22:29:06.560 -04:00 [ERR] [System.Diagnostics.Process] [Render]:    at SharpDX.Direct3D11.D3D11.CreateDevice(Adapter adapterRef, DriverType driverType, IntPtr software, DeviceCreationFlags flags, FeatureLevel[] featureLevelsRef, Int32 featureLevels, Int32 sDKVersion, Device deviceOut, FeatureLevel& featureLevelRef, DeviceContext& immediateContextOut)
2021-10-11 22:29:06.560 -04:00 [ERR] [System.Diagnostics.Process] [Render]:    at SharpDX.Direct3D11.Device.CreateDevice(Adapter adapter, DriverType driverType, DeviceCreationFlags flags, FeatureLevel[] featureLevels)
2021-10-11 22:29:06.560 -04:00 [ERR] [System.Diagnostics.Process] [Render]:    at BrowserHost.Renderer.DxHandler.Initialise(Int64 adapterLuid)
2021-10-11 22:29:06.560 -04:00 [ERR] [System.Diagnostics.Process] [Render]:    at BrowserHost.Renderer.Program.Run(RenderProcessArguments args)
2021-10-11 22:29:06.560 -04:00 [ERR] [System.Diagnostics.Process] [Render]:    at BrowserHost.Renderer.Program.Main(String[] rawArgs)
